version: '3.7'

volumes:
  mongo_vol:

networks:
  dudanw:
    driver: bridge


services:
  rotten:
    image: teclinux/rotten-potatoes:latest
    ports:
      - 5000:5000
    networks:
      - dudanw
    depends_on:
      - mongodb  
    environment:
      MONGODB_DB: admin
      MONGODB_HOST: mongodb
      MONGODB_PORT: "27017"
      MONGODB_USERNAME: mongouser
      MONGODB_PASSWORD: mongopwd
     # MONGODB_URI: mongodb://mongouser:mongopwd@mongodb:27017/admin
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_vol:/data/db  
    networks:
      - dudanw
    environment:
          MONGO_INITDB_ROOT_USERNAME: mongouser
          MONGO_INITDB_ROOT_PASSWORD: mongopwd
